// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqOSFt5yRZHm7VVPBlpyy1cCfT_HwLDOM',
    appId: '1:1096541213862:web:c55b91c3e998c67ce6d067',
    messagingSenderId: '1096541213862',
    projectId: 'adarsh-lms-platform',
    authDomain: 'adarsh-lms-platform.firebaseapp.com',
    storageBucket: 'adarsh-lms-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApYOE5Ni4lHAFt97-rZFMpnA9HDu2ftmA',
    appId: '1:1096541213862:android:bdffbd3a2383cc5ae6d067',
    messagingSenderId: '1096541213862',
    projectId: 'adarsh-lms-platform',
    storageBucket: 'adarsh-lms-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjKfhGv1X4oCIx_pZoTu7GP5A1Rft5jIo',
    appId: '1:1096541213862:ios:5c0e3a4fe0a43d26e6d067',
    messagingSenderId: '1096541213862',
    projectId: 'adarsh-lms-platform',
    storageBucket: 'adarsh-lms-platform.firebasestorage.app',
    iosBundleId: 'com.example.friendsLms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjKfhGv1X4oCIx_pZoTu7GP5A1Rft5jIo',
    appId: '1:1096541213862:ios:5c0e3a4fe0a43d26e6d067',
    messagingSenderId: '1096541213862',
    projectId: 'adarsh-lms-platform',
    storageBucket: 'adarsh-lms-platform.firebasestorage.app',
    iosBundleId: 'com.example.friendsLms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqOSFt5yRZHm7VVPBlpyy1cCfT_HwLDOM',
    appId: '1:1096541213862:web:96f49c1a1c1243a2e6d067',
    messagingSenderId: '1096541213862',
    projectId: 'adarsh-lms-platform',
    authDomain: 'adarsh-lms-platform.firebaseapp.com',
    storageBucket: 'adarsh-lms-platform.firebasestorage.app',
  );

}